import Foundation
import SwiftData

// MARK: Sendable snapshots

public struct DeliveryInfo: Sendable, Equatable {
    public let id: String
    public let plannedWorkoutId: String
    public let profileId: String
    public let packageHash: String
    public let status: String
    public let revision: Int
    public let lastClientSequence: Int
}

public struct WorkoutPackageInfo: Sendable, Equatable, Identifiable {
    public var id: String { packageId }
    public let packageId: String
    public let deliveryId: String
    public let plannedWorkoutId: String
    public let planId: String
    public let planVersionId: String
    public let title: String
    public let scheduledForDate: String
    public let timezone: String
    public let revision: Int
    public let expiresAt: String?
    public let packageHash: String
}

public struct PackageSetInfo: Sendable, Equatable {
    public let setNumber: Int
    public let reps: Int?
    public let repsMin: Int?
    public let repsMax: Int?
    public let durationSeconds: Int?
    public let distanceMeters: String?
    public let restSeconds: Int?
    public let weightKg: String?
    public let loadValue: String?
    public let loadUnit: String?
    public let loadMode: String?
    public let rir: String?
    public let rpe: String?
    public let notes: String?
}

public struct PackageExerciseInfo: Sendable, Equatable, Identifiable {
    public var id: Int { exerciseOrder }
    public let exerciseOrder: Int
    public let name: String
    public let notes: String?
    public let sets: [PackageSetInfo]
}

public struct WorkoutDraft: Sendable, Equatable {
    public let deliveryId: String
    public let packageId: String
    public let clientEventId: String
    public let packageHash: String
    public let status: String
    public let startedAt: String
    public let pausedAt: String?
    public let averageHeartRateBpm: Int?
    public let caloriesBurned: String?
    public let notes: String?
    public let checkpointSequence: Int
    public let corruptReasonCode: String?
    public let updatedAt: String

    /// Final operations are queued; capture is locked until the server confirms.
    public var isFinalPending: Bool { status == "completion_pending" || status == "aborted_pending" }
}

public struct DraftSet: Sendable, Equatable, Identifiable {
    public var id: String { "\(exerciseOrder)-\(setNumber)" }
    public let deliveryId: String
    public let exerciseOrder: Int
    public var setNumber: Int
    public let plannedSetNumber: Int
    public var reps: Int
    public var rir: String?
    public var rpe: String?
    public var weightKg: String
    public var loadDetailsJSON: String?
    public var durationSeconds: Int?
    public var distanceMeters: String?
    public var restSeconds: Int?
    public var notes: String?
    public var checkpointSequence: Int?
    public var completed: Bool

    public init(deliveryId: String, exerciseOrder: Int, setNumber: Int, plannedSetNumber: Int, reps: Int, rir: String? = nil, rpe: String? = nil,
                weightKg: String, loadDetailsJSON: String? = nil, durationSeconds: Int? = nil, distanceMeters: String? = nil,
                restSeconds: Int? = nil, notes: String? = nil, checkpointSequence: Int? = nil, completed: Bool = false) {
        self.deliveryId = deliveryId
        self.exerciseOrder = exerciseOrder
        self.setNumber = setNumber
        self.plannedSetNumber = plannedSetNumber
        self.reps = reps
        self.rir = rir
        self.rpe = rpe
        self.weightKg = weightKg
        self.loadDetailsJSON = loadDetailsJSON
        self.durationSeconds = durationSeconds
        self.distanceMeters = distanceMeters
        self.restSeconds = restSeconds
        self.notes = notes
        self.checkpointSequence = checkpointSequence
        self.completed = completed
    }
}

/// Identifiers generated by the caller so the store stays deterministic in tests.
public struct DraftIdentifiers: Sendable {
    public let clientSubmissionId: String
    public let clientEventId: String
    public let startOperationId: String
    public let startKey: String

    public init(clientSubmissionId: String = UUID().uuidString.lowercased(), clientEventId: String = UUID().uuidString.lowercased(),
                startOperationId: String = UUID().uuidString.lowercased(), startKey: String = UUID().uuidString.lowercased()) {
        self.clientSubmissionId = clientSubmissionId
        self.clientEventId = clientEventId
        self.startOperationId = startOperationId
        self.startKey = startKey
    }
}

/// Draft metric rules shared by save, checkpoint and recovery (android `validateDraftSet`).
public enum DraftRules {
    public static func validate(_ set: DraftSet, requireCompletedMetrics: Bool) throws {
        let minimumReps = requireCompletedMetrics ? 1 : 0
        guard (minimumReps...10_000).contains(set.reps) else {
            throw AppFailure(.validationError, "Las repeticiones deben estar entre \(minimumReps) y 10 000.", retryable: false)
        }
        guard let weight = LoadCalculator.parse(set.weightKg), weight <= 2000 else {
            throw AppFailure(.validationError, "La carga debe estar entre 0 y 2000 kg.", retryable: false)
        }
        if let rir = set.rir, LoadCalculator.parse(rir).map({ $0 <= 10 }) != true {
            throw AppFailure(.validationError, "RIR debe estar entre 0 y 10.", retryable: false)
        }
        if let rpe = set.rpe, LoadCalculator.parse(rpe).map({ $0 >= 1 && $0 <= 10 }) != true {
            throw AppFailure(.validationError, "RPE debe estar entre 1 y 10.", retryable: false)
        }
        if let duration = set.durationSeconds, !(1...86_400).contains(duration) {
            throw AppFailure(.validationError, "La duración debe estar entre 1 y 86 400 segundos.", retryable: false)
        }
        if let rest = set.restSeconds, !(0...86_400).contains(rest) {
            throw AppFailure(.validationError, "El descanso debe estar entre 0 y 86 400 segundos.", retryable: false)
        }
        if let distance = set.distanceMeters, LoadCalculator.parse(distance) == nil {
            throw AppFailure(.validationError, "La distancia debe ser un número no negativo.", retryable: false)
        }
    }
}

// MARK: Store operations

extension LocalStore {
    static let localActiveDeliveryStates: Set<String> = ["started_pending", "started"]

    func clearWorkoutData(_ scope: String) throws {
        try modelContext.delete(model: WorkoutPackageModel.self, where: #Predicate { $0.accountScope == scope })
        try modelContext.delete(model: PackageExerciseModel.self, where: #Predicate { $0.accountScope == scope })
        try modelContext.delete(model: PackageSetModel.self, where: #Predicate { $0.accountScope == scope })
        try modelContext.delete(model: WorkoutDraftModel.self, where: #Predicate { $0.accountScope == scope })
        try modelContext.delete(model: DraftSetModel.self, where: #Predicate { $0.accountScope == scope })
    }

    // MARK: Reads

    public func delivery(_ scope: String, id: String) -> DeliveryInfo? {
        let key = scopedKey(scope, id)
        return (try? fetch(#Predicate<DeliveryModel> { $0.key == key }).first).map {
            DeliveryInfo(id: $0.id, plannedWorkoutId: $0.plannedWorkoutId, profileId: $0.profileId, packageHash: $0.packageHash,
                         status: $0.status, revision: $0.revision, lastClientSequence: $0.lastClientSequence)
        }
    }

    public func plannedWorkout(_ scope: String, id: String) -> PlannedWorkout? {
        plannedWorkouts(scope).first { $0.id == id }
    }

    public func packages(_ scope: String) -> [WorkoutPackageInfo] {
        ((try? fetch(#Predicate<WorkoutPackageModel> { $0.accountScope == scope })) ?? []).map(Self.snapshot)
    }

    public func packageForPlanned(_ scope: String, plannedId: String) -> WorkoutPackageInfo? {
        (try? fetch(#Predicate<WorkoutPackageModel> { $0.accountScope == scope && $0.plannedWorkoutId == plannedId }).first).map(Self.snapshot)
    }

    public func packageForDelivery(_ scope: String, deliveryId: String) -> WorkoutPackageInfo? {
        (try? packageModel(scope, deliveryId: deliveryId)).flatMap { $0 }.map(Self.snapshot)
    }

    public func packageExercises(_ scope: String, packageId: String) -> [PackageExerciseInfo] {
        let exercises = (try? fetch(#Predicate<PackageExerciseModel> { $0.accountScope == scope && $0.packageId == packageId },
                                    sort: [SortDescriptor(\.exerciseOrder)])) ?? []
        let sets = (try? fetch(#Predicate<PackageSetModel> { $0.accountScope == scope && $0.packageId == packageId },
                               sort: [SortDescriptor(\.setNumber)])) ?? []
        return exercises.map { exercise in
            PackageExerciseInfo(exerciseOrder: exercise.exerciseOrder, name: exercise.name, notes: exercise.notes,
                                sets: sets.filter { $0.exerciseOrder == exercise.exerciseOrder }.map {
                                    PackageSetInfo(setNumber: $0.setNumber, reps: $0.reps, repsMin: $0.repsMin, repsMax: $0.repsMax,
                                                   durationSeconds: $0.durationSeconds, distanceMeters: $0.distanceMeters,
                                                   restSeconds: $0.restSeconds, weightKg: $0.weightKg, loadValue: $0.loadValue,
                                                   loadUnit: $0.loadUnit, loadMode: $0.loadMode, rir: $0.rir, rpe: $0.rpe, notes: $0.notes)
                                })
        }
    }

    public func draft(_ scope: String, deliveryId: String) -> WorkoutDraft? {
        (try? draftModel(scope, deliveryId)).flatMap { $0 }.map(Self.snapshot)
    }

    /// Most recently touched draft of the account (android `observeActiveDraft`).
    public func activeDraft(_ scope: String) -> WorkoutDraft? {
        (try? fetch(#Predicate<WorkoutDraftModel> { $0.accountScope == scope }, sort: [SortDescriptor(\.updatedAt, order: .reverse)], limit: 1).first)
            .map(Self.snapshot)
    }

    public func draftSets(_ scope: String, deliveryId: String) -> [DraftSet] {
        ((try? draftSetModels(scope, deliveryId)) ?? []).map(Self.snapshot)
    }

    // MARK: Download

    /// Marks the planned workout as conflicting when a newer revision exists but an active draft keeps the old package.
    public func recordPackageConflict(_ scope: String, plannedId: String, package: WorkoutPackageInfo, plannedTitle: String,
                                      plannedDate: String, serverRevision: Int, now: Date = Date()) throws {
        try write {
            let conflict = PlanningConflictModel(
                scope: scope, entityId: plannedId, entityType: "package", localRevision: package.revision, serverRevision: serverRevision,
                changedFields: "package_revision_conflict:revision", localName: "\(package.title) · \(package.scheduledForDate)",
                remoteName: "\(plannedTitle) · \(plannedDate)", createdAt: iso(now)
            )
            let key = conflict.key
            try modelContext.delete(model: PlanningConflictModel.self, where: #Predicate { $0.key == key })
            modelContext.insert(conflict)
            let plannedKey = scopedKey(scope, plannedId)
            try fetch(#Predicate<PlannedWorkoutModel> { $0.key == plannedKey }).first?.status = "conflict"
        }
    }

    /// Stores a verified package with its delivery. When the ack could not be sent, the delivery is kept
    /// as `acknowledged_pending` and the ack is queued in the same unit.
    public func storeDownloadedPackage(_ scope: String, delivery: DeliveryDTO, package: VerifiedPackage, stalePackageId: String?,
                                       queuedAck: (key: String, payload: JSONValue)?, now: Date = Date()) throws {
        try write {
            try upsertDelivery(scope, delivery)
            if let stalePackageId { try deletePackage(scope, packageId: stalePackageId) }
            try deletePackage(scope, packageId: package.value.packageId)
            modelContext.insert(WorkoutPackageModel(scope: scope, deliveryId: delivery.id, package: package.value, hash: package.calculatedHash, verifiedAt: iso(now)))
            for exercise in package.value.exercises {
                modelContext.insert(PackageExerciseModel(scope: scope, packageId: package.value.packageId, exerciseOrder: exercise.exerciseOrder,
                                                         name: exercise.name, notes: exercise.notes))
                for (index, set) in exercise.sets.enumerated() {
                    modelContext.insert(PackageSetModel(scope: scope, packageId: package.value.packageId, exerciseOrder: exercise.exerciseOrder,
                                                        setNumber: set["set_number"]?.intValue ?? index + 1, json: set))
                }
            }
            if let queuedAck {
                try insertPending(scope, actionType: "companion_ack", entityId: delivery.id, idempotencyKey: queuedAck.key,
                                  payloadJSON: queuedAck.payload.encoded(), now: now)
            }
        }
    }

    private func deletePackage(_ scope: String, packageId: String) throws {
        let key = scopedKey(scope, packageId)
        try modelContext.delete(model: WorkoutPackageModel.self, where: #Predicate { $0.key == key })
        try modelContext.delete(model: PackageExerciseModel.self, where: #Predicate { $0.accountScope == scope && $0.packageId == packageId })
        try modelContext.delete(model: PackageSetModel.self, where: #Predicate { $0.accountScope == scope && $0.packageId == packageId })
    }

    // MARK: Draft lifecycle

    /// Creates the local draft from the verified package and queues `companion_start` (android `startWorkout`).
    /// Returns the existing draft when one is already present for the delivery.
    public func startDraft(_ scope: String, deliveryId: String, ids: DraftIdentifiers = DraftIdentifiers(), now: Date = Date()) throws -> (draft: WorkoutDraft, created: Bool) {
        try write {
            if let existing = try draftModel(scope, deliveryId) { return (Self.snapshot(existing), false) }
            let deliveryKey = scopedKey(scope, deliveryId)
            guard let delivery = try fetch(#Predicate<DeliveryModel> { $0.key == deliveryKey }).first else {
                throw AppFailure(.localStorageError, "No se encontró la entrega descargada.", retryable: false)
            }
            guard let package = try packageModel(scope, deliveryId: deliveryId) else {
                throw AppFailure(.localStorageError, "Falta el package local.", retryable: false)
            }
            guard delivery.packageHash.lowercased() == package.packageHash.lowercased() else {
                throw AppFailure(.packageHashMismatch, "La entrega local no corresponde al package verificado.", retryable: false)
            }
            if let expires = package.expiresAt.flatMap(DisplayText.parseInstant), expires < now {
                throw AppFailure(.packageExpired, "El entrenamiento descargado ya expiró.", retryable: false)
            }
            let packageId = package.packageId
            let packageSets = try fetch(#Predicate<PackageSetModel> { $0.accountScope == scope && $0.packageId == packageId })
            guard !packageSets.isEmpty else {
                throw AppFailure(.draftCorrupt, "El package descargado no contiene series recuperables.", retryable: false)
            }
            let draft = WorkoutDraftModel(
                scope: scope, deliveryId: deliveryId, packageId: packageId, packageHash: package.packageHash, startedAt: iso(now),
                expiresAt: iso(now.addingTimeInterval(7 * 86_400)), checkpointSequence: delivery.lastClientSequence,
                clientSubmissionId: ids.clientSubmissionId, clientEventId: ids.clientEventId
            )
            modelContext.insert(draft)
            for set in packageSets {
                let row = DraftSetModel(scope: scope, deliveryId: deliveryId, exerciseOrder: set.exerciseOrder, setNumber: set.setNumber,
                                        plannedSetNumber: set.setNumber, reps: set.reps ?? set.repsMin ?? 1,
                                        weightKg: set.weightKg.flatMap(LoadCalculator.parse).map(LoadCalculator.storageWeight) ?? "0", updatedAt: iso(now))
                row.durationSeconds = set.durationSeconds
                row.distanceMeters = set.distanceMeters
                row.restSeconds = set.restSeconds
                modelContext.insert(row)
            }
            try refreshPayloadHash(draft)
            let operation = CompanionPayload.operation(id: ids.startOperationId, baseRevision: delivery.revision)
            try insertPending(scope, actionType: "companion_start", entityId: deliveryId, idempotencyKey: ids.startKey, payloadJSON: operation.encoded(), now: now)
            delivery.status = "started_pending"
            delivery.revision += 1
            return (Self.snapshot(draft), true)
        }
    }

    /// Saves one set locally; a completed set stays completed (android `saveSet`).
    public func saveDraftSet(_ scope: String, _ value: DraftSet, now: Date = Date()) throws {
        try DraftRules.validate(value, requireCompletedMetrics: false)
        try write {
            guard let draft = try draftModel(scope, value.deliveryId), !draft.isLocked else { return }
            let row = try draftSetModel(scope, value) ?? {
                let created = DraftSetModel(scope: scope, deliveryId: value.deliveryId, exerciseOrder: value.exerciseOrder, setNumber: value.setNumber,
                                            plannedSetNumber: value.plannedSetNumber, reps: value.reps, weightKg: value.weightKg, updatedAt: iso(now))
                modelContext.insert(created)
                return created
            }()
            apply(value, to: row, now: now)
            row.completed = row.completed || value.completed
            if !["paused", "pending_sync", "completion_pending", "aborted_pending", "corrupt"].contains(draft.status) { draft.status = "saved" }
            draft.updatedAt = iso(now)
            try refreshPayloadHash(draft)
        }
    }

    /// Adds a copy of a set as the next set number of its exercise.
    public func duplicateDraftSet(_ scope: String, _ source: DraftSet, now: Date = Date()) throws {
        let deliveryId = source.deliveryId
        let order = source.exerciseOrder
        let next = ((try? fetch(#Predicate<DraftSetModel> { $0.accountScope == scope && $0.deliveryId == deliveryId && $0.exerciseOrder == order }))?
            .map(\.setNumber).max() ?? 0) + 1
        var copy = source
        copy.setNumber = next
        copy.checkpointSequence = nil
        copy.completed = false
        try saveDraftSet(scope, copy, now: now)
    }

    public func updateDraftSummary(_ scope: String, deliveryId: String, heartRate: Int?, calories: String?, notes: String?, now: Date = Date()) throws {
        if let heartRate, !(20...250).contains(heartRate) {
            throw AppFailure(.validationError, "La frecuencia cardiaca debe estar entre 20 y 250.", retryable: false)
        }
        let caloriesText = calories?.trimmingCharacters(in: .whitespaces).isEmpty == false ? calories : nil
        if let caloriesText, LoadCalculator.parse(caloriesText) == nil {
            throw AppFailure(.validationError, "Las calorías deben ser un número no negativo.", retryable: false)
        }
        try write {
            guard let draft = try draftModel(scope, deliveryId), !draft.isLocked else { return }
            draft.averageHeartRateBpm = heartRate
            draft.caloriesBurned = caloriesText
            draft.notes = notes.map { String($0.prefix(5000)) }
            draft.updatedAt = iso(now)
            try refreshPayloadHash(draft)
        }
    }

    /// Completes a set and queues its `set_completed` progress event. An already checkpointed set is only saved.
    @discardableResult
    public func checkpointDraftSet(_ scope: String, _ value: DraftSet, eventId: String = UUID().uuidString.lowercased(),
                                   key: String = UUID().uuidString.lowercased(), now: Date = Date()) throws -> Bool {
        try DraftRules.validate(value, requireCompletedMetrics: true)
        return try write {
            guard let draft = try draftModel(scope, value.deliveryId), !draft.isLocked,
                  let row = try draftSetModel(scope, value) else { return false }
            apply(value, to: row, now: now)
            if row.checkpointSequence != nil {
                row.completed = true
                draft.updatedAt = iso(now)
                try refreshPayloadHash(draft)
                return false
            }
            let sequence = draft.checkpointSequence + 1
            row.checkpointSequence = sequence
            row.completed = true
            var payload: [(String, JSONValue)] = [
                ("exercise_order", .number(String(row.exerciseOrder))),
                ("set_number", .number(String(row.setNumber))),
                ("completed_reps", .number(String(row.reps))),
                ("weight_kg", .number(row.weightKg)),
            ]
            if let rir = row.rir { payload.append(("rir", .number(rir))) }
            if let rpe = row.rpe { payload.append(("rpe", .number(rpe))) }
            if let rest = row.restSeconds { payload.append(("rest_seconds", .number(String(rest)))) }
            let request = CompanionPayload.progress(eventId: eventId, sequence: sequence, eventType: "set_completed", occurredAt: iso(now), payload: .object(payload))
            try insertPending(scope, actionType: "companion_progress", entityId: value.deliveryId, idempotencyKey: key, payloadJSON: request.encoded(), now: now)
            draft.checkpointSequence = sequence
            draft.status = "pending_sync"
            draft.updatedAt = iso(now)
            try refreshPayloadHash(draft)
            return true
        }
    }

    @discardableResult
    public func pauseOrResume(_ scope: String, deliveryId: String, pause: Bool, eventId: String = UUID().uuidString.lowercased(),
                              key: String = UUID().uuidString.lowercased(), now: Date = Date()) throws -> Bool {
        let desired = pause ? "paused" : "active"
        return try write {
            guard let draft = try draftModel(scope, deliveryId), !draft.isLocked, draft.status != desired else { return false }
            let sequence = draft.checkpointSequence + 1
            let request = CompanionPayload.progress(eventId: eventId, sequence: sequence, eventType: pause ? "paused" : "resumed",
                                                    occurredAt: iso(now), payload: .object([]))
            try insertPending(scope, actionType: "companion_progress", entityId: deliveryId, idempotencyKey: key, payloadJSON: request.encoded(), now: now)
            draft.status = desired
            draft.pausedAt = pause ? iso(now) : nil
            draft.checkpointSequence = sequence
            draft.updatedAt = iso(now)
            return true
        }
    }

    /// Queues `companion_abort`; the draft stays locked until the server confirms.
    @discardableResult
    public func abortDraft(_ scope: String, deliveryId: String, operationId: String = UUID().uuidString.lowercased(),
                           key: String = UUID().uuidString.lowercased(), now: Date = Date()) throws -> Bool {
        try write {
            let deliveryKey = scopedKey(scope, deliveryId)
            guard let delivery = try fetch(#Predicate<DeliveryModel> { $0.key == deliveryKey }).first else { return false }
            let draft = try draftModel(scope, deliveryId)
            if draft?.isFinalPending == true { return false }
            let operation = CompanionPayload.operation(id: operationId, baseRevision: delivery.revision, reasonCode: "user_cancelled")
            try insertPending(scope, actionType: "companion_abort", entityId: deliveryId, idempotencyKey: key, payloadJSON: operation.encoded(), now: now)
            draft?.status = "aborted_pending"
            draft?.updatedAt = iso(now)
            return true
        }
    }

    /// Builds the completed workout from completed sets, queues `companion_complete`, records a pending
    /// history entry and marks the planned workout as completed, all in one unit (android `completeWorkout`).
    @discardableResult
    public func completeDraft(_ scope: String, deliveryId: String, key: String = UUID().uuidString.lowercased(), now: Date = Date()) throws -> Bool {
        try write {
            guard let draft = try draftModel(scope, deliveryId) else {
                throw AppFailure(.draftCorrupt, "No se encontró el borrador.", retryable: false)
            }
            if draft.status == "completion_pending" { return false }
            if draft.status == "aborted_pending" {
                throw AppFailure(.revisionConflict, "La sesión ya está pendiente de cancelación.", retryable: false)
            }
            let deliveryKey = scopedKey(scope, deliveryId)
            guard let delivery = try fetch(#Predicate<DeliveryModel> { $0.key == deliveryKey }).first else {
                throw AppFailure(.localStorageError, "No se encontró la entrega.", retryable: false)
            }
            guard let package = try packageModel(scope, deliveryId: deliveryId) else {
                throw AppFailure(.localStorageError, "Falta el package local.", retryable: false)
            }
            let packageId = package.packageId
            let exercises = try fetch(#Predicate<PackageExerciseModel> { $0.accountScope == scope && $0.packageId == packageId },
                                      sort: [SortDescriptor(\.exerciseOrder)])
            let sets = try draftSetModels(scope, deliveryId).filter(\.completed)
            guard !sets.isEmpty else { throw AppFailure(.validationError, "Completa al menos una serie.", retryable: false) }
            for set in sets { try DraftRules.validate(Self.snapshot(set), requireCompletedMetrics: true) }
            let started = DisplayText.parseInstant(draft.startedAt) ?? now
            let duration = max(1, Int(now.timeIntervalSince(started)))
            var exerciseValues: [JSONValue] = []
            var historyExercises: [HistoryRow.Exercise] = []
            for exercise in exercises {
                let done = sets.filter { $0.exerciseOrder == exercise.exerciseOrder }
                guard !done.isEmpty else { continue }
                var members: [(String, JSONValue)] = [
                    ("exercise_order", .number(String(exercise.exerciseOrder))),
                    ("planned_exercise_order", .number(String(exercise.exerciseOrder))),
                    ("name", .string(exercise.name)),
                ]
                if let notes = exercise.notes { members.append(("notes", .string(notes))) }
                members.append(("sets", .array(done.map(Self.completedSetJSON))))
                exerciseValues.append(.object(members))
                historyExercises.append(HistoryRow.Exercise(order: exercise.exerciseOrder, name: exercise.name, notes: exercise.notes, sets: done.map {
                    let details = $0.loadDetailsJSON.flatMap { try? JSONValue.parse($0) }
                    return HistoryRow.Set(number: $0.setNumber, weightKg: $0.weightKg, displayValue: details?["display_total"]?["value"]?.stringValue,
                                          displayUnit: details?["display_total"]?["unit"]?.stringValue,
                                          loadMode: details?["load_mode"]?.stringValue ?? "direct_total", reps: $0.reps, rir: $0.rir, rpe: $0.rpe,
                                          restSeconds: $0.restSeconds, durationSeconds: $0.durationSeconds.map(String.init),
                                          distanceMeters: $0.distanceMeters, notes: $0.notes)
                }))
            }
            var result: [(String, JSONValue)] = [
                ("schema_version", .string(contractVersion)),
                ("client_event_id", .string(draft.clientEventId)),
                ("planned_workout_id", .string(package.plannedWorkoutId)),
                ("training_plan_id", .string(package.planId)),
                ("training_plan_version_id", .string(package.planVersionId)),
                ("started_at", .string(draft.startedAt)),
                ("completed_at", .string(iso(now))),
                ("timezone", .string(package.timezone)),
                ("duration_seconds", .number(String(duration))),
            ]
            if let heartRate = draft.averageHeartRateBpm { result.append(("average_heart_rate_bpm", .number(String(heartRate)))) }
            if let calories = draft.caloriesBurned { result.append(("calories_burned", .number(calories))) }
            if let notes = draft.notes, !notes.isEmpty { result.append(("notes", .string(notes))) }
            result.append(("exercises", .array(exerciseValues)))
            let request = CompanionPayload.completion(eventId: draft.clientEventId, packageHash: draft.packageHash,
                                                      baseRevision: delivery.revision, result: .object(result))
            try insertPending(scope, actionType: "companion_complete", entityId: deliveryId, idempotencyKey: key, payloadJSON: request.encoded(), now: now)
            draft.status = "completion_pending"
            draft.updatedAt = iso(now)
            try insertHistory(scope, HistoryRow(
                publicId: draft.clientEventId, clientEventId: draft.clientEventId, plannedWorkoutId: package.plannedWorkoutId,
                planId: package.planId, planVersionId: package.planVersionId, name: package.title, startedAt: draft.startedAt,
                completedAt: iso(now), timezone: package.timezone, durationSeconds: duration, notes: draft.notes,
                source: "companion", syncStatus: "pending", exercises: historyExercises
            ), now: now)
            let plannedKey = scopedKey(scope, package.plannedWorkoutId)
            if let planned = try fetch(#Predicate<PlannedWorkoutModel> { $0.key == plannedKey }).first {
                planned.status = "completed"
                planned.updatedAt = iso(now)
            }
            return true
        }
    }

    /// Deletes an isolated draft and its queued operations; only allowed for drafts marked corrupt.
    public func discardCorruptDraft(_ scope: String, deliveryId: String) throws {
        try write {
            guard let draft = try draftModel(scope, deliveryId) else { return }
            guard draft.status == "corrupt" else {
                throw AppFailure(.validationError, "Solo puede descartarse un borrador marcado como corrupto.", retryable: false)
            }
            try modelContext.delete(model: PendingActionModel.self, where: #Predicate { $0.accountScope == scope && $0.entityId == deliveryId })
            try deleteDraft(scope, deliveryId)
        }
    }

    // MARK: Recovery validation

    /// Re-validates a recovered draft. Failures isolate it as `corrupt` with a sanitized reason; a corrupt
    /// draft that validates again is restored (android `validateRecoveredDraft`).
    @discardableResult
    public func validateDraft(_ scope: String, deliveryId: String, currentScope: String?, deviceId: String, now: Date = Date()) throws -> WorkoutDraft? {
        try write {
            guard let draft = try draftModel(scope, deliveryId) else { return nil }
            let reason = try draftFailure(draft, currentScope: currentScope, deviceId: deviceId, now: now)
            if let reason {
                if draft.status != "corrupt" || draft.corruptReasonCode != reason {
                    draft.status = "corrupt"
                    draft.corruptReasonCode = reason
                    draft.updatedAt = iso(now)
                }
            } else if draft.status == "corrupt" {
                draft.status = "active"
                draft.corruptReasonCode = nil
                draft.updatedAt = iso(now)
            }
            return Self.snapshot(draft)
        }
    }

    private func draftFailure(_ draft: WorkoutDraftModel, currentScope: String?, deviceId: String, now: Date) throws -> String? {
        let scope = draft.accountScope
        let deliveryId = draft.deliveryId
        guard draft.schemaVersion == contractVersion else { return "draft_schema_incompatible" }
        if !draft.isFinalPending, let expires = DisplayText.parseInstant(draft.expiresAt), expires < now { return "draft_expired" }
        guard let package = try packageModel(scope, deliveryId: deliveryId) else { return "draft_package_missing" }
        guard package.packageId == draft.packageId, package.packageHash.lowercased() == draft.packageHash.lowercased() else { return "draft_package_mismatch" }
        let deliveryKey = scopedKey(scope, deliveryId)
        guard let delivery = try fetch(#Predicate<DeliveryModel> { $0.key == deliveryKey }).first else { return "draft_delivery_missing" }
        guard delivery.packageHash.lowercased() == draft.packageHash.lowercased() else { return "draft_package_mismatch" }
        let packageId = package.packageId
        guard try modelContext.fetchCount(FetchDescriptor<PackageExerciseModel>(predicate: #Predicate { $0.accountScope == scope && $0.packageId == packageId })) > 0,
              try modelContext.fetchCount(FetchDescriptor<PackageSetModel>(predicate: #Predicate { $0.accountScope == scope && $0.packageId == packageId })) > 0
        else { return "draft_package_content_missing" }
        let sets = try draftSetModels(scope, deliveryId)
        guard !sets.isEmpty else { return "draft_sets_missing" }
        for set in sets {
            guard set.accountScope == scope, set.deliveryId == deliveryId else { return "draft_account_scope_mismatch" }
            guard set.reps >= 0, LoadCalculator.parse(set.weightKg) != nil else { return "draft_metric_invalid" }
            if let rir = set.rir, LoadCalculator.parse(rir).map({ $0 <= 10 }) != true { return "draft_metric_invalid" }
            if let rpe = set.rpe, LoadCalculator.parse(rpe).map({ $0 >= 1 && $0 <= 10 }) != true { return "draft_metric_invalid" }
            if let details = set.loadDetailsJSON, (try? JSONValue.parse(details)) == nil { return "draft_metric_invalid" }
        }
        guard draft.payloadHash == Self.payloadHash(draft, sets) else { return "draft_payload_hash_mismatch" }
        let pendingStart = try modelContext.fetchCount(FetchDescriptor<PendingActionModel>(predicate: #Predicate {
            $0.accountScope == scope && $0.entityId == deliveryId && $0.actionType == "companion_start"
        })) > 0
        guard pendingStart || Self.localActiveDeliveryStates.contains(delivery.status) || draft.isFinalPending else { return "draft_start_state_missing" }
        if let currentScope, currentScope != scope { return "draft_account_scope_mismatch" }
        if currentScope == scope {
            guard let account = try fetch(#Predicate<AccountModel> { $0.scope == scope }).first else { return "draft_account_missing" }
            guard account.deviceId == deviceId else { return "draft_device_mismatch" }
            guard let profile = try fetch(#Predicate<LocalProfileModel> { $0.accountScope == scope }).first, profile.profileId != nil else { return "draft_profile_missing" }
            guard profile.profileId == delivery.profileId else { return "draft_profile_mismatch" }
        }
        return nil
    }

    // MARK: Queue handler results

    public func applyDelivery(_ scope: String, _ dto: DeliveryDTO) throws {
        try write { try upsertDelivery(scope, dto) }
    }

    /// The server confirmed the cancellation: keep its delivery state and drop the local draft.
    public func applyAbortConfirmed(_ scope: String, _ dto: DeliveryDTO) throws {
        try write {
            try upsertDelivery(scope, dto)
            try deleteDraft(scope, dto.id)
        }
    }

    /// The server accepted the result: replace the pending local history entry with the server session.
    public func applyCompletion(_ scope: String, deliveryId: String, _ response: CompletionResponse, now: Date = Date()) throws {
        try write {
            try upsertDelivery(scope, response.delivery)
            let completed = response.completedWorkout
            let localEventId = try draftModel(scope, deliveryId)?.clientEventId
            if let eventId = completed.clientEventId ?? localEventId {
                try deleteHistory(scope, publicId: eventId)
            }
            try upsertRecent(scope, completed)
            if let id = completed.id {
                try insertHistory(scope, HistoryRow(completed: completed, publicId: id), now: now)
            }
            try deleteDraft(scope, deliveryId)
        }
    }

    /// Account device id, used to check that a remote delivery belongs to this device.
    public func accountDeviceId(_ scope: String) -> String? {
        (try? fetch(#Predicate<AccountModel> { $0.scope == scope }).first)?.deviceId
    }

    // MARK: Helpers

    private func draftModel(_ scope: String, _ deliveryId: String) throws -> WorkoutDraftModel? {
        let key = scopedKey(scope, deliveryId)
        return try fetch(#Predicate<WorkoutDraftModel> { $0.key == key }).first
    }

    private func draftSetModels(_ scope: String, _ deliveryId: String) throws -> [DraftSetModel] {
        try fetch(#Predicate<DraftSetModel> { $0.accountScope == scope && $0.deliveryId == deliveryId },
                  sort: [SortDescriptor(\.exerciseOrder), SortDescriptor(\.setNumber)])
    }

    private func draftSetModel(_ scope: String, _ value: DraftSet) throws -> DraftSetModel? {
        let key = DraftSetModel.key(scope, value.deliveryId, value.exerciseOrder, value.setNumber)
        return try fetch(#Predicate<DraftSetModel> { $0.key == key }).first
    }

    private func packageModel(_ scope: String, deliveryId: String) throws -> WorkoutPackageModel? {
        try fetch(#Predicate<WorkoutPackageModel> { $0.accountScope == scope && $0.deliveryId == deliveryId }).first
    }

    private func deleteDraft(_ scope: String, _ deliveryId: String) throws {
        let key = scopedKey(scope, deliveryId)
        try modelContext.delete(model: WorkoutDraftModel.self, where: #Predicate { $0.key == key })
        try modelContext.delete(model: DraftSetModel.self, where: #Predicate { $0.accountScope == scope && $0.deliveryId == deliveryId })
    }

    private func apply(_ value: DraftSet, to row: DraftSetModel, now: Date) {
        row.reps = value.reps
        row.rir = value.rir
        row.rpe = value.rpe
        row.weightKg = value.weightKg
        row.loadDetailsJSON = value.loadDetailsJSON
        row.durationSeconds = value.durationSeconds
        row.distanceMeters = value.distanceMeters
        row.restSeconds = value.restSeconds
        row.notes = value.notes.map { String($0.prefix(2000)) }
        row.updatedAt = iso(now)
    }

    private func refreshPayloadHash(_ draft: WorkoutDraftModel) throws {
        draft.payloadHash = Self.payloadHash(draft, try draftSetModels(draft.accountScope, draft.deliveryId))
    }

    /// Integrity hash over the draft and its sets (android `draftPayloadHash`).
    static func payloadHash(_ draft: WorkoutDraftModel, _ sets: [DraftSetModel]) -> String {
        func text(_ value: String?) -> JSONValue { value.map(JSONValue.string) ?? .null }
        func number(_ value: Int?) -> JSONValue { value.map { .number(String($0)) } ?? .null }
        let ordered = sets.sorted { ($0.exerciseOrder, $0.setNumber) < ($1.exerciseOrder, $1.setNumber) }
        return CanonicalJSON.sha256(.object([
            ("package_hash", .string(draft.packageHash)),
            ("client_submission_id", .string(draft.clientSubmissionId)),
            ("client_event_id", .string(draft.clientEventId)),
            ("started_at", .string(draft.startedAt)),
            ("average_heart_rate_bpm", number(draft.averageHeartRateBpm)),
            ("calories_burned", text(draft.caloriesBurned)),
            ("notes", text(draft.notes)),
            ("sets", .array(ordered.map { set in
                .object([
                    ("exercise_order", number(set.exerciseOrder)), ("set_number", number(set.setNumber)),
                    ("planned_set_number", number(set.plannedSetNumber)), ("reps", number(set.reps)),
                    ("rir", text(set.rir)), ("rpe", text(set.rpe)), ("weight_kg", .string(set.weightKg)),
                    ("load_details", text(set.loadDetailsJSON)), ("duration_seconds", number(set.durationSeconds)),
                    ("distance_meters", text(set.distanceMeters)), ("rest_seconds", number(set.restSeconds)),
                    ("notes", text(set.notes)), ("checkpoint_sequence", number(set.checkpointSequence)),
                    ("completed", .bool(set.completed)),
                ])
            })),
        ]))
    }

    private static func completedSetJSON(_ set: DraftSetModel) -> JSONValue {
        var members: [(String, JSONValue)] = [
            ("set_number", .number(String(set.setNumber))),
            ("planned_set_number", .number(String(set.plannedSetNumber))),
            ("weight_kg", .number(set.weightKg)),
        ]
        if let details = set.loadDetailsJSON.flatMap({ try? JSONValue.parse($0) }) { members.append(("load_details", details)) }
        members.append(("reps", .number(String(set.reps))))
        if let rir = set.rir { members.append(("rir", .number(rir))) }
        if let rpe = set.rpe { members.append(("rpe", .number(rpe))) }
        if let rest = set.restSeconds { members.append(("rest_seconds", .number(String(rest)))) }
        if let duration = set.durationSeconds { members.append(("duration_seconds", .number(String(duration)))) }
        if let notes = set.notes, !notes.isEmpty { members.append(("notes", .string(notes))) }
        return .object(members)
    }

    private static func snapshot(_ row: WorkoutPackageModel) -> WorkoutPackageInfo {
        WorkoutPackageInfo(packageId: row.packageId, deliveryId: row.deliveryId, plannedWorkoutId: row.plannedWorkoutId, planId: row.planId,
                           planVersionId: row.planVersionId, title: row.title, scheduledForDate: row.scheduledForDate, timezone: row.timezone,
                           revision: row.revision, expiresAt: row.expiresAt, packageHash: row.packageHash)
    }

    private static func snapshot(_ row: WorkoutDraftModel) -> WorkoutDraft {
        WorkoutDraft(deliveryId: row.deliveryId, packageId: row.packageId, clientEventId: row.clientEventId, packageHash: row.packageHash,
                     status: row.status, startedAt: row.startedAt, pausedAt: row.pausedAt, averageHeartRateBpm: row.averageHeartRateBpm,
                     caloriesBurned: row.caloriesBurned, notes: row.notes, checkpointSequence: row.checkpointSequence,
                     corruptReasonCode: row.corruptReasonCode, updatedAt: row.updatedAt)
    }

    private static func snapshot(_ row: DraftSetModel) -> DraftSet {
        DraftSet(deliveryId: row.deliveryId, exerciseOrder: row.exerciseOrder, setNumber: row.setNumber, plannedSetNumber: row.plannedSetNumber,
                 reps: row.reps, rir: row.rir, rpe: row.rpe, weightKg: row.weightKg, loadDetailsJSON: row.loadDetailsJSON,
                 durationSeconds: row.durationSeconds, distanceMeters: row.distanceMeters, restSeconds: row.restSeconds, notes: row.notes,
                 checkpointSequence: row.checkpointSequence, completed: row.completed)
    }
}

extension WorkoutDraftModel {
    var isFinalPending: Bool { status == "completion_pending" || status == "aborted_pending" }
    /// Final or isolated drafts never accept capture edits.
    var isLocked: Bool { isFinalPending || status == "corrupt" }
}
