"""Official gym orchestration over the existing training domain.

Mutations are caller-committed so mapping, version and projection are atomic.
User row locks serialize active selection, import retries and session starts.
"""
import copy
import hashlib
import json
import uuid

from flask import current_app
from itsdangerous import BadData, URLSafeTimedSerializer
from sqlalchemy.orm import selectinload

from app.extensions import db
from app.models import Exercise, ExerciseAlias, TrainingPlan, TrainingPlanVersion, User
from app.services.exercise_identity import normalize_exercise_name
from app.services.importers.routine_draft import RoutineImportDraft, RoutineParseError, validate_draft_shape
from app.services.mobile_planning import validate_exercises
from app.services.training_plans import replace_mobile_workouts_from_document, serialize_training_plan
from app.services.validation import validate_json_document


class GymError(ValueError):
    def __init__(self, message, status=400):
        super().__init__(message)
        self.status = status


def lock_user(user_id):
    user = db.session.execute(db.select(User).where(User.id == user_id).with_for_update()).scalar_one_or_none()
    if user is None:
        raise GymError("Usuario no encontrado.", 404)
    return user


def owned_plan(user_id, public_id, lock=False):
    query = db.select(TrainingPlan).where(TrainingPlan.deleted_at.is_(None), TrainingPlan.user_id == user_id, TrainingPlan.public_id == public_id)
    if lock:
        query = query.with_for_update().execution_options(populate_existing=True)
    plan = db.session.execute(query).scalar_one_or_none()
    if plan is None:
        raise GymError("Rutina no encontrada.", 404)
    return plan


def catalog(user_id):
    return db.session.execute(db.select(Exercise).where(Exercise.user_id == user_id).options(selectinload(Exercise.aliases)).order_by(Exercise.canonical_name)).scalars().all()


def resolve_draft(draft, user_id):
    """Exact owner names/aliases only. Unknown names require an explicit decision."""
    validate_draft_shape(draft)
    identities = catalog(user_id)
    by_id = {item.public_id: item for item in identities}
    by_name = {name: item for item in identities for name in [item.normalized_name, *(alias.normalized_name for alias in item.aliases)]}
    # Explicit bilingual aliases only; never fuzzy-match a movement automatically.
    for alias, canonical in {"bench press": "press banca", "lat pulldown": "jalón al pecho"}.items():
        if alias not in by_name and canonical in by_name:
            by_name[alias] = by_name[canonical]
    draft.unresolved = []
    for day in draft.days:
        for exercise in day["exercises"]:
            resolved_id = exercise.get("resolved_exercise_id")
            item = by_id.get(resolved_id) if resolved_id else by_name.get(normalize_exercise_name(exercise["raw_name"]))
            if resolved_id and item is None:
                raise GymError("Ejercicio no encontrado.", 404)
            if item:
                exercise["resolved_exercise_id"] = item.public_id
                exercise["name"] = item.canonical_name
            elif exercise.get("create_new") is True:
                exercise["name"] = exercise["raw_name"].strip()
            else:
                draft.unresolved.append(exercise["raw_name"])
    return draft


def standard_document(draft, user_id):
    validate_draft_shape(draft)
    weeks = []
    for offset in range(0, len(draft.days), 7):
        days = []
        for index, day in enumerate(draft.days[offset:offset + 7], 1):
            exercises = []
            for order, exercise in enumerate(day["exercises"], 1):
                item = {"name": exercise.get("name") or exercise["raw_name"], "exercise_order": order, "sets": copy.deepcopy(exercise["sets"])}
                if exercise.get("resolved_exercise_id"):
                    item["exercise_id"] = exercise["resolved_exercise_id"]
                if exercise.get("notes"):
                    item["notes"] = exercise["notes"]
                # Validate and calculate prescribed load using the existing service.
                normalized = validate_exercises([item])[0]
                # IDs generated by the mutable editor must not defeat content dedup.
                normalized.pop("id", None)
                normalized["exercise_order"] = order
                for planned_set in normalized["sets"]:
                    planned_set.pop("id", None)
                exercises.append(normalized)
            days.append({"day_number": index, "name": day["name"].strip(), "exercises": exercises, **({"notes": day["notes"]} if day.get("notes") else {})})
        weeks.append({"week_number": len(weeks) + 1, "days": days})
    document = {"schema_version": "1.0", "record_type": "training_plan", "user_id": user_id, "source_type": "manual_generated", "data": {"name": draft.program["name"].strip(), "weeks": weeks}}
    if draft.program.get("description"):
        document["data"]["description"] = draft.program["description"]
    validate_json_document(document, "training_plan")
    return document


def _serializer():
    return URLSafeTimedSerializer(current_app.config["SECRET_KEY"], salt="gym-program-preview-v1")


def _fingerprint(draft, user_id, plan_id, revision):
    content = {"draft": draft.to_dict(), "owner": user_id, "plan": plan_id, "revision": revision}
    return hashlib.sha256(json.dumps(content, sort_keys=True, ensure_ascii=False, allow_nan=False).encode()).hexdigest()


def preview_token(draft, user_id, plan_id=None, revision=None):
    return _serializer().dumps(_fingerprint(draft, user_id, plan_id, revision))


def confirm_program(draft, user_id, token, *, plan_id=None, base_revision=None):
    try:
        valid = _serializer().loads(token, max_age=3600)
    except BadData as error:
        raise GymError("El preview expiró; revísalo de nuevo.") from error
    if valid != _fingerprint(draft, user_id, plan_id, base_revision):
        raise GymError("El contenido cambió; revisa un nuevo preview.")
    resolve_draft(draft, user_id)
    if draft.unresolved:
        raise GymError("Resuelve todos los ejercicios antes de confirmar.")
    # Validate before any catalog mutation, then validate again with real identities.
    standard_document(draft, user_id)
    from app.services.gym_import_sources import promote_source
    source = promote_source(draft, user_id)
    lock_user(user_id)
    identities = catalog(user_id)
    by_name = {name: item for item in identities for name in [item.normalized_name, *(alias.normalized_name for alias in item.aliases)]}
    by_id = {item.public_id: item for item in identities}
    for day in draft.days:
        for exercise in day["exercises"]:
            raw = normalize_exercise_name(exercise["raw_name"])
            item = by_id.get(exercise.get("resolved_exercise_id")) or by_name.get(raw)
            if item is None:
                item = Exercise(user_id=user_id, public_id=str(uuid.uuid4()), canonical_name=exercise["name"], normalized_name=raw)
                db.session.add(item)
                db.session.flush()
                by_id[item.public_id] = item
                by_name[raw] = item
            if raw in by_name and by_name[raw].id != item.id:
                raise GymError("Ese alias ya corresponde a otro ejercicio.")
            if raw not in by_name:
                db.session.add(ExerciseAlias(user_id=user_id, exercise_id=item.id, alias_name=exercise["raw_name"], normalized_name=raw))
                by_name[raw] = item
            exercise["resolved_exercise_id"] = item.public_id
            exercise["name"] = item.canonical_name
    document = standard_document(draft, user_id)
    plan, duplicate = publish_program_document(document, user_id, plan_id=plan_id, base_revision=base_revision)
    version = db.session.execute(db.select(TrainingPlanVersion).where(TrainingPlanVersion.user_id == user_id, TrainingPlanVersion.training_plan_id == plan.id, TrainingPlanVersion.version_number == plan.active_version_number)).scalar_one()
    if source:
        source.import_status = "duplicate" if duplicate else "imported"
        source.detected_type = "training_plan"
        already_linked = db.session.execute(db.select(TrainingPlanVersion.id).where(TrainingPlanVersion.source_file_id == source.id)).first()
        if not already_linked and not version.source_file_id:
            version.source_file_id = source.id
    from app.services.import_audit import ImportAuditService
    audit = ImportAuditService()
    summary = {"total": 1, "inserts": int(not duplicate and not plan_id), "updates": int(not duplicate and bool(plan_id)), "skips": int(duplicate)}
    run = audit.create_pending(user_id=user_id, target_type="training_plan", source_type="uploaded" if source else "manual_generated", payload_sha256=draft.source_sha256 or version.sha256, plan_sha256=version.sha256, summary=summary, metadata={"mode": "gym_program", "route": "/gym/programs/confirm", "contract_version": "1.0"})
    audit.finalize_succeeded(run, summary)
    return plan, duplicate


def publish_program_document(document, user_id, *, plan_id=None, base_revision=None):
    """Validate -> immutable version -> current projection. Caller owns commit."""
    validate_json_document(document, "training_plan")
    if document["user_id"] != user_id:
        raise GymError("El documento no corresponde al usuario.")
    digest = hashlib.sha256(serialize_training_plan(document)).hexdigest()
    plan = owned_plan(user_id, plan_id, lock=True) if plan_id else None
    if plan is None:
        duplicates = db.session.execute(db.select(TrainingPlanVersion).join(TrainingPlan).where(TrainingPlanVersion.user_id == user_id, TrainingPlan.deleted_at.is_(None), TrainingPlan.user_id == user_id, TrainingPlanVersion.sha256 == digest)).scalars().all()
        if duplicates:
            return duplicates[0].training_plan, True
        plan = TrainingPlan(user_id=user_id, name=document["data"]["name"])
        db.session.add(plan)
        db.session.flush()
    else:
        current = db.session.execute(db.select(TrainingPlanVersion).where(TrainingPlanVersion.user_id == user_id, TrainingPlanVersion.training_plan_id == plan.id, TrainingPlanVersion.version_number == plan.active_version_number)).scalar_one_or_none()
        if current and current.sha256 == digest:
            return plan, True
        if base_revision != plan.revision:
            raise GymError("La rutina cambió; vuelve a abrir el editor.", 409)
    duplicate = db.session.execute(db.select(TrainingPlanVersion).where(TrainingPlanVersion.user_id == user_id, TrainingPlanVersion.training_plan_id == plan.id, TrainingPlanVersion.sha256 == digest)).scalar_one_or_none()
    if duplicate:
        version = duplicate
    else:
        latest = db.session.execute(db.select(db.func.max(TrainingPlanVersion.version_number)).where(TrainingPlanVersion.user_id == user_id, TrainingPlanVersion.training_plan_id == plan.id)).scalar_one()
        version = TrainingPlanVersion(user_id=user_id, training_plan_id=plan.id, version_number=(latest or 0) + 1, created_by_user_id=user_id, change_reason="Programa confirmado desde Gym", schema_version="1.0", sha256=digest, content=copy.deepcopy(document))
        db.session.add(version)
    plan.active_version_number = version.version_number
    plan.name = document["data"]["name"]
    plan.description = document["data"].get("description")
    plan.revision += 1
    replace_mobile_workouts_from_document(plan, document, user_id)
    if not db.session.execute(db.select(TrainingPlan.id).where(TrainingPlan.deleted_at.is_(None), TrainingPlan.user_id == user_id, TrainingPlan.gym_active.is_(True))).first():
        plan.gym_active = True
    db.session.flush()
    db.session.expire(plan, ["workouts", "versions"])
    from app.services.mobile_planning import _record_plan
    _record_plan(plan, None)
    return plan, False


def activate_program(user_id, public_id):
    lock_user(user_id)
    plan = owned_plan(user_id, public_id, lock=True)
    db.session.execute(db.update(TrainingPlan).where(TrainingPlan.deleted_at.is_(None), TrainingPlan.user_id == user_id).values(gym_active=False))
    plan.gym_active = True
    plan.status = "active"
    return plan


# Code-versioned, editable structural examples; no globally mutable DB templates.
PRESETS = {
    "full-body-v1": {"name": "Full Body · template v1", "days": [("Full Body A", ["Sentadilla", "Press banca", "Remo"]), ("Full Body B", ["Peso muerto rumano", "Press militar", "Jalón al pecho"])]},
    "upper-lower-v1": {"name": "Upper / Lower · template v1", "days": [("Upper A", ["Press banca", "Remo"]), ("Lower A", ["Sentadilla", "Peso muerto rumano"]), ("Upper B", ["Press militar", "Jalón al pecho"]), ("Lower B", ["Prensa", "Curl femoral"])]},
    "ppl-v1": {"name": "Push Pull Legs · template v1", "days": [("Push", ["Press banca", "Press militar"]), ("Pull", ["Remo", "Jalón al pecho"]), ("Legs", ["Sentadilla", "Curl femoral"])]},
}


def preset_draft(key):
    if key not in PRESETS:
        raise GymError("Template no encontrado.", 404)
    preset = PRESETS[key]
    return RoutineImportDraft({"name": preset["name"]}, [{"name": day, "exercises": [{"raw_name": name, "create_new": True, "sets": [{"set_number": i + 1, "reps_min": 6, "reps_max": 8} for i in range(3)]} for name in exercises]} for day, exercises in preset["days"]])
