"""Nutrition Intelligence: additive local catalog and historical snapshots."""
from alembic import op
import sqlalchemy as sa
import uuid

revision = "20261009_0044"
down_revision = "20260928_0043"
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_catalog_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('license', sa.String(length=200), nullable=False),
    sa.Column('active_revision', sa.String(length=64), nullable=True),
    sa.Column('previous_revision', sa.String(length=64), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrients',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('group', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_catalog_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['food_catalog_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'revision', name='uq_food_catalog_revision')
    )
    op.create_table('meal_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('state', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('accepted_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('meal_drafts', schema=None) as batch_op:
        batch_op.create_index('ix_meal_draft_owner', ['user_id', 'state'], unique=False)

    op.create_table('catalog_foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('catalog_revision_id', sa.Integer(), nullable=False),
    sa.Column('source_food_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('preparation', sa.String(length=200), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_revision_id'], ['food_catalog_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_revision_id', 'source_food_id', name='uq_catalog_food_identity'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('catalog_foods', schema=None) as batch_op:
        batch_op.create_index('ix_catalog_food_search', ['catalog_revision_id', 'name'], unique=False)

    op.create_table('food_nutrients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('nutrient_id', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.CheckConstraint("state IN ('known','unknown','trace','below_limit')", name='ck_food_nutrient_state'),
    sa.CheckConstraint('value IS NULL OR value >= 0', name='ck_food_nutrient_nonnegative'),
    sa.ForeignKeyConstraint(['food_id'], ['catalog_foods.id'], ),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id', 'nutrient_id', name='uq_food_nutrient')
    )
    op.create_table('food_servings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('source_serving_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=12), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_food_serving_positive'),
    sa.ForeignKeyConstraint(['food_id'], ['catalog_foods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id', 'source_serving_id', name='uq_food_serving')
    )
    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_event_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('projection_item_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['projection_item_id'], ['nutrition_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projection_item_id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('user_id', 'client_event_id', name='uq_meal_log_event')
    )
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.create_index('ix_meal_log_owner_date', ['user_id', 'local_date'], unique=False)

    with op.batch_alter_table('daily_nutrition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authority', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('authority_baseline_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('nutrition_summary_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('food_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutrition_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutrition_snapshot_json', sa.JSON(), nullable=True))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('revision', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('nutrition_snapshot_json', sa.JSON(), nullable=True))
        batch_op.create_unique_constraint('uq_recipes_public_id', ['public_id'])

    connection = op.get_bind()
    recipes = sa.table("recipes", sa.column("id", sa.Integer()), sa.column("public_id", sa.String(36)))
    for row in connection.execute(sa.select(recipes.c.id)):
        connection.execute(recipes.update().where(recipes.c.id == row.id).values(public_id=str(uuid.uuid4())))
    with op.batch_alter_table("recipes") as batch_op:
        batch_op.alter_column("public_id", existing_type=sa.String(36), nullable=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_recipes_public_id', type_='unique')
        batch_op.drop_column('nutrition_snapshot_json')
        batch_op.drop_column('revision')
        batch_op.drop_column('public_id')

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_column('nutrition_snapshot_json')

    with op.batch_alter_table('food_products', schema=None) as batch_op:
        batch_op.drop_column('nutrition_json')

    with op.batch_alter_table('daily_nutrition', schema=None) as batch_op:
        batch_op.drop_column('nutrition_summary_json')
        batch_op.drop_column('authority_baseline_json')
        batch_op.drop_column('authority')

    # DROP TABLE removes its indexes atomically. MariaDB may use the owner
    # index to enforce the user FK and rejects dropping that index separately.
    op.drop_table('meal_logs')
    op.drop_table('food_servings')
    op.drop_table('food_nutrients')
    op.drop_table('catalog_foods')
    op.drop_table('meal_drafts')
    op.drop_table('food_catalog_revisions')
    op.drop_table('nutrients')
    op.drop_table('food_catalog_sources')
    # ### end Alembic commands ###
